#! /usr/bin/Rscript
local({r <- getOption("repos")
    r["CRAN"] <- "http://cran.us.r-project.org" 
    options(repos=r)
})
update.packages(checkBuilt=TRUE, ask=FALSE)
install.packages('ggplot2')
install.packages('knitr', dependencies = TRUE)
install.packages('ggmap')
install.packages("extrafont")
install.packages("jsonlite")
install.packages("xtable")
install.packages("doMC")
install.packages("speedglm")
install.packages("glmnet")
install.packages("Matrix")
install.packages("RJDBC")
install.packages("ROCR")
install.packages("e1071")
install.packages("SparseM")
install.packages("Matching")
install.packages("RColorBrewer")
install.packages("gpclib")
install.packages('rgdal')
print('RUN sudo apt-get install libproj-dev libgdal-dev BEFORE INSTALLING rgdal !!!!!')
install.packages("maptools")
library(extrafont)
font_import(prompt = FALSE)
print('RUN sudo apt-get install libproj-dev libgdal-dev BEFORE INSTALLING rgdal !!!!!')

