//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:15 PM MESZ 
//


package edu.harvard.i2b2.core.datavo.pdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * One row of data from the concept_dimension table.
 * 
 * <p>Java class for concept_dimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="concept_dimensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="concept_path" type="{http://www.i2b2.org/xsd/hive/pdo/}Concept_PathType"/>
 *         &lt;element name="concept_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Concept_CdType" minOccurs="0"/>
 *         &lt;element name="name_char" type="{http://www.i2b2.org/xsd/hive/pdo/}Name_CharType" minOccurs="0"/>
 *         &lt;element name="concept_blob" type="{http://www.i2b2.org/xsd/hive/pdo/}Concept_BlobType" minOccurs="0"/>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}annotationGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "concept_dimensionType", propOrder = {
    "conceptPath",
    "conceptCd",
    "nameChar",
    "conceptBlob",
    "updateDate",
    "downloadDate",
    "importDate",
    "sourcesystemCd",
    "uploadId"
})
public class ConceptDimensionType {

    @XmlElement(name = "concept_path", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String conceptPath;
    @XmlElement(name = "concept_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String conceptCd;
    @XmlElement(name = "name_char")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nameChar;
    @XmlElement(name = "concept_blob")
    protected ConceptBlobType conceptBlob;
    @XmlElement(name = "update_date")
    protected XMLGregorianCalendar updateDate;
    @XmlElement(name = "download_date")
    protected XMLGregorianCalendar downloadDate;
    @XmlElement(name = "import_date")
    protected XMLGregorianCalendar importDate;
    @XmlElement(name = "sourcesystem_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourcesystemCd;
    @XmlElement(name = "upload_id")
    protected Integer uploadId;

    /**
     * Gets the value of the conceptPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConceptPath() {
        return conceptPath;
    }

    /**
     * Sets the value of the conceptPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConceptPath(String value) {
        this.conceptPath = value;
    }

    /**
     * Gets the value of the conceptCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConceptCd() {
        return conceptCd;
    }

    /**
     * Sets the value of the conceptCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConceptCd(String value) {
        this.conceptCd = value;
    }

    /**
     * Gets the value of the nameChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameChar() {
        return nameChar;
    }

    /**
     * Sets the value of the nameChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameChar(String value) {
        this.nameChar = value;
    }

    /**
     * Gets the value of the conceptBlob property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptBlobType }
     *     
     */
    public ConceptBlobType getConceptBlob() {
        return conceptBlob;
    }

    /**
     * Sets the value of the conceptBlob property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptBlobType }
     *     
     */
    public void setConceptBlob(ConceptBlobType value) {
        this.conceptBlob = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the downloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDownloadDate() {
        return downloadDate;
    }

    /**
     * Sets the value of the downloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDownloadDate(XMLGregorianCalendar value) {
        this.downloadDate = value;
    }

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportDate(XMLGregorianCalendar value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the sourcesystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesystemCd() {
        return sourcesystemCd;
    }

    /**
     * Sets the value of the sourcesystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesystemCd(String value) {
        this.sourcesystemCd = value;
    }

    /**
     * Gets the value of the uploadId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * Sets the value of the uploadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUploadId(Integer value) {
        this.uploadId = value;
    }

}
