//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:15 PM MESZ 
//


package edu.harvard.i2b2.core.datavo.pdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * One row of data from the observation_fact table.
 * 
 * <p>Java class for observation_factType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="observation_factType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}encounter_idChoice"/>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}patient_idChoice"/>
 *         &lt;element name="concept_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Concept_CdType"/>
 *         &lt;element name="provider_id" type="{http://www.i2b2.org/xsd/hive/pdo/}Provider_IdType"/>
 *         &lt;element name="start_date" type="{http://www.i2b2.org/xsd/hive/pdo/}Start_DateType"/>
 *         &lt;element name="modifier_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Modifier_CdType"/>
 *         &lt;element name="valtype_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}ValType_CdType" minOccurs="0"/>
 *         &lt;element name="tval_char" type="{http://www.i2b2.org/xsd/hive/pdo/}TVal_CharType" minOccurs="0"/>
 *         &lt;element name="nval_num" type="{http://www.i2b2.org/xsd/hive/pdo/}NVal_NumType" minOccurs="0"/>
 *         &lt;element name="valueflag_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}ValueFlag_CdType" minOccurs="0"/>
 *         &lt;element name="quantity_num" type="{http://www.i2b2.org/xsd/hive/pdo/}Quantity_NumType" minOccurs="0"/>
 *         &lt;element name="units_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Units_CdType" minOccurs="0"/>
 *         &lt;element name="end_date" type="{http://www.i2b2.org/xsd/hive/pdo/}End_DateType" minOccurs="0"/>
 *         &lt;element name="location_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Location_CdType" minOccurs="0"/>
 *         &lt;element name="confidence_num" type="{http://www.i2b2.org/xsd/hive/pdo/}Confidence_NumType" minOccurs="0"/>
 *         &lt;element name="observation_blob" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}annotationGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "observation_factType", propOrder = {
    "encounterNum",
    "encounterId",
    "encounterIde",
    "patientNum",
    "patientId",
    "patientIde",
    "conceptCd",
    "providerId",
    "startDate",
    "modifierCd",
    "valtypeCd",
    "tvalChar",
    "nvalNum",
    "valueflagCd",
    "quantityNum",
    "unitsCd",
    "endDate",
    "locationCd",
    "confidenceNum",
    "observationBlob",
    "updateDate",
    "downloadDate",
    "importDate",
    "sourcesystemCd",
    "uploadId"
})
public class ObservationFactType {

    @XmlElement(name = "encounter_num")
    protected Integer encounterNum;
    @XmlElement(name = "encounter_id")
    protected EncounterIdType encounterId;
    @XmlElement(name = "encounter_ide")
    protected EncounterIdeType encounterIde;
    @XmlElement(name = "patient_num")
    protected Integer patientNum;
    @XmlElement(name = "patient_id")
    protected PatientIdType patientId;
    @XmlElement(name = "patient_ide")
    protected PatientIdeType patientIde;
    @XmlElement(name = "concept_cd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String conceptCd;
    @XmlElement(name = "provider_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String providerId;
    @XmlElement(name = "start_date", required = true)
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "modifier_cd", required = true)
    protected String modifierCd;
    @XmlElement(name = "valtype_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valtypeCd;
    @XmlElement(name = "tval_char")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tvalChar;
    @XmlElement(name = "nval_num")
    protected Double nvalNum;
    @XmlElement(name = "valueflag_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valueflagCd;
    @XmlElement(name = "quantity_num")
    protected Double quantityNum;
    @XmlElement(name = "units_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String unitsCd;
    @XmlElement(name = "end_date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "location_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locationCd;
    @XmlElement(name = "confidence_num")
    protected Double confidenceNum;
    @XmlElement(name = "observation_blob")
    protected Object observationBlob;
    @XmlElement(name = "update_date")
    protected XMLGregorianCalendar updateDate;
    @XmlElement(name = "download_date")
    protected XMLGregorianCalendar downloadDate;
    @XmlElement(name = "import_date")
    protected XMLGregorianCalendar importDate;
    @XmlElement(name = "sourcesystem_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourcesystemCd;
    @XmlElement(name = "upload_id")
    protected Integer uploadId;

    /**
     * Gets the value of the encounterNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEncounterNum() {
        return encounterNum;
    }

    /**
     * Sets the value of the encounterNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEncounterNum(Integer value) {
        this.encounterNum = value;
    }

    /**
     * Gets the value of the encounterId property.
     * 
     * @return
     *     possible object is
     *     {@link EncounterIdType }
     *     
     */
    public EncounterIdType getEncounterId() {
        return encounterId;
    }

    /**
     * Sets the value of the encounterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncounterIdType }
     *     
     */
    public void setEncounterId(EncounterIdType value) {
        this.encounterId = value;
    }

    /**
     * Gets the value of the encounterIde property.
     * 
     * @return
     *     possible object is
     *     {@link EncounterIdeType }
     *     
     */
    public EncounterIdeType getEncounterIde() {
        return encounterIde;
    }

    /**
     * Sets the value of the encounterIde property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncounterIdeType }
     *     
     */
    public void setEncounterIde(EncounterIdeType value) {
        this.encounterIde = value;
    }

    /**
     * Gets the value of the patientNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPatientNum() {
        return patientNum;
    }

    /**
     * Sets the value of the patientNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPatientNum(Integer value) {
        this.patientNum = value;
    }

    /**
     * Gets the value of the patientId property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdType }
     *     
     */
    public PatientIdType getPatientId() {
        return patientId;
    }

    /**
     * Sets the value of the patientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdType }
     *     
     */
    public void setPatientId(PatientIdType value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the patientIde property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdeType }
     *     
     */
    public PatientIdeType getPatientIde() {
        return patientIde;
    }

    /**
     * Sets the value of the patientIde property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdeType }
     *     
     */
    public void setPatientIde(PatientIdeType value) {
        this.patientIde = value;
    }

    /**
     * Gets the value of the conceptCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConceptCd() {
        return conceptCd;
    }

    /**
     * Sets the value of the conceptCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConceptCd(String value) {
        this.conceptCd = value;
    }

    /**
     * Gets the value of the providerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * Sets the value of the providerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderId(String value) {
        this.providerId = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the modifierCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifierCd() {
        return modifierCd;
    }

    /**
     * Sets the value of the modifierCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifierCd(String value) {
        this.modifierCd = value;
    }

    /**
     * Gets the value of the valtypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValtypeCd() {
        return valtypeCd;
    }

    /**
     * Sets the value of the valtypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValtypeCd(String value) {
        this.valtypeCd = value;
    }

    /**
     * Gets the value of the tvalChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTvalChar() {
        return tvalChar;
    }

    /**
     * Sets the value of the tvalChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTvalChar(String value) {
        this.tvalChar = value;
    }

    /**
     * Gets the value of the nvalNum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNvalNum() {
        return nvalNum;
    }

    /**
     * Sets the value of the nvalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNvalNum(Double value) {
        this.nvalNum = value;
    }

    /**
     * Gets the value of the valueflagCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueflagCd() {
        return valueflagCd;
    }

    /**
     * Sets the value of the valueflagCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueflagCd(String value) {
        this.valueflagCd = value;
    }

    /**
     * Gets the value of the quantityNum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQuantityNum() {
        return quantityNum;
    }

    /**
     * Sets the value of the quantityNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQuantityNum(Double value) {
        this.quantityNum = value;
    }

    /**
     * Gets the value of the unitsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitsCd() {
        return unitsCd;
    }

    /**
     * Sets the value of the unitsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitsCd(String value) {
        this.unitsCd = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the locationCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCd() {
        return locationCd;
    }

    /**
     * Sets the value of the locationCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationCd(String value) {
        this.locationCd = value;
    }

    /**
     * Gets the value of the confidenceNum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConfidenceNum() {
        return confidenceNum;
    }

    /**
     * Sets the value of the confidenceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConfidenceNum(Double value) {
        this.confidenceNum = value;
    }

    /**
     * Gets the value of the observationBlob property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getObservationBlob() {
        return observationBlob;
    }

    /**
     * Sets the value of the observationBlob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setObservationBlob(Object value) {
        this.observationBlob = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the downloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDownloadDate() {
        return downloadDate;
    }

    /**
     * Sets the value of the downloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDownloadDate(XMLGregorianCalendar value) {
        this.downloadDate = value;
    }

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportDate(XMLGregorianCalendar value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the sourcesystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesystemCd() {
        return sourcesystemCd;
    }

    /**
     * Sets the value of the sourcesystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesystemCd(String value) {
        this.sourcesystemCd = value;
    }

    /**
     * Gets the value of the uploadId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * Sets the value of the uploadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUploadId(Integer value) {
        this.uploadId = value;
    }

}
