//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:15 PM MESZ 
//


package edu.harvard.i2b2.core.datavo.pdo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * May contain any number of visit_dimension, concept_dimension,
 *                 provider_dimension, patient_dimension and observation_fact elements. They can occur
 *                 in any order.
 * 
 * <p>Java class for patient_dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patient_dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="visit_dimension_set" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="visit_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}visit_dimensionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="concept_dimension_set" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="concept_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}concept_dimensionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="provider_dimension_set" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="provider_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}provider_dimensionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="patient_dimension_set" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="patient_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}patient_dimensionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="observation_fact_set" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="observation_fact" type="{http://www.i2b2.org/xsd/hive/pdo/}observation_factType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="filter_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="concept_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="provider_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patient_dataType", propOrder = {
    "visitDimensionSet",
    "conceptDimensionSet",
    "providerDimensionSet",
    "patientDimensionSet",
    "observationFactSet"
})
public class PatientDataType {

    @XmlElement(name = "visit_dimension_set")
    protected PatientDataType.VisitDimensionSet visitDimensionSet;
    @XmlElement(name = "concept_dimension_set")
    protected PatientDataType.ConceptDimensionSet conceptDimensionSet;
    @XmlElement(name = "provider_dimension_set")
    protected PatientDataType.ProviderDimensionSet providerDimensionSet;
    @XmlElement(name = "patient_dimension_set")
    protected PatientDataType.PatientDimensionSet patientDimensionSet;
    @XmlElement(name = "observation_fact_set")
    protected List<PatientDataType.ObservationFactSet> observationFactSet;

    /**
     * Gets the value of the visitDimensionSet property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDataType.VisitDimensionSet }
     *     
     */
    public PatientDataType.VisitDimensionSet getVisitDimensionSet() {
        return visitDimensionSet;
    }

    /**
     * Sets the value of the visitDimensionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDataType.VisitDimensionSet }
     *     
     */
    public void setVisitDimensionSet(PatientDataType.VisitDimensionSet value) {
        this.visitDimensionSet = value;
    }

    /**
     * Gets the value of the conceptDimensionSet property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDataType.ConceptDimensionSet }
     *     
     */
    public PatientDataType.ConceptDimensionSet getConceptDimensionSet() {
        return conceptDimensionSet;
    }

    /**
     * Sets the value of the conceptDimensionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDataType.ConceptDimensionSet }
     *     
     */
    public void setConceptDimensionSet(PatientDataType.ConceptDimensionSet value) {
        this.conceptDimensionSet = value;
    }

    /**
     * Gets the value of the providerDimensionSet property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDataType.ProviderDimensionSet }
     *     
     */
    public PatientDataType.ProviderDimensionSet getProviderDimensionSet() {
        return providerDimensionSet;
    }

    /**
     * Sets the value of the providerDimensionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDataType.ProviderDimensionSet }
     *     
     */
    public void setProviderDimensionSet(PatientDataType.ProviderDimensionSet value) {
        this.providerDimensionSet = value;
    }

    /**
     * Gets the value of the patientDimensionSet property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDataType.PatientDimensionSet }
     *     
     */
    public PatientDataType.PatientDimensionSet getPatientDimensionSet() {
        return patientDimensionSet;
    }

    /**
     * Sets the value of the patientDimensionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDataType.PatientDimensionSet }
     *     
     */
    public void setPatientDimensionSet(PatientDataType.PatientDimensionSet value) {
        this.patientDimensionSet = value;
    }

    /**
     * Gets the value of the observationFactSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observationFactSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservationFactSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientDataType.ObservationFactSet }
     * 
     * 
     */
    public List<PatientDataType.ObservationFactSet> getObservationFactSet() {
        if (observationFactSet == null) {
            observationFactSet = new ArrayList<PatientDataType.ObservationFactSet>();
        }
        return this.observationFactSet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="concept_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}concept_dimensionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "conceptDimension"
    })
    public static class ConceptDimensionSet {

        @XmlElement(name = "concept_dimension", required = true)
        protected List<ConceptDimensionType> conceptDimension;

        /**
         * Gets the value of the conceptDimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the conceptDimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConceptDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConceptDimensionType }
         * 
         * 
         */
        public List<ConceptDimensionType> getConceptDimension() {
            if (conceptDimension == null) {
                conceptDimension = new ArrayList<ConceptDimensionType>();
            }
            return this.conceptDimension;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="observation_fact" type="{http://www.i2b2.org/xsd/hive/pdo/}observation_factType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="filter_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="concept_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="provider_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "observationFact"
    })
    public static class ObservationFactSet {

        @XmlElement(name = "observation_fact", required = true)
        protected List<ObservationFactType> observationFact;
        @XmlAttribute
        protected String path;
        @XmlAttribute(name = "filter_name")
        protected String filterName;
        @XmlAttribute(name = "concept_name")
        protected String conceptName;
        @XmlAttribute(name = "provider_id")
        protected String providerId;

        /**
         * Gets the value of the observationFact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the observationFact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObservationFact().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationFactType }
         * 
         * 
         */
        public List<ObservationFactType> getObservationFact() {
            if (observationFact == null) {
                observationFact = new ArrayList<ObservationFactType>();
            }
            return this.observationFact;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

        /**
         * Gets the value of the filterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterName() {
            return filterName;
        }

        /**
         * Sets the value of the filterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterName(String value) {
            this.filterName = value;
        }

        /**
         * Gets the value of the conceptName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConceptName() {
            return conceptName;
        }

        /**
         * Sets the value of the conceptName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConceptName(String value) {
            this.conceptName = value;
        }

        /**
         * Gets the value of the providerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProviderId() {
            return providerId;
        }

        /**
         * Sets the value of the providerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProviderId(String value) {
            this.providerId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="patient_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}patient_dimensionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "patientDimension"
    })
    public static class PatientDimensionSet {

        @XmlElement(name = "patient_dimension", required = true)
        protected List<PatientDimensionType> patientDimension;

        /**
         * Gets the value of the patientDimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the patientDimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPatientDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PatientDimensionType }
         * 
         * 
         */
        public List<PatientDimensionType> getPatientDimension() {
            if (patientDimension == null) {
                patientDimension = new ArrayList<PatientDimensionType>();
            }
            return this.patientDimension;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="provider_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}provider_dimensionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "providerDimension"
    })
    public static class ProviderDimensionSet {

        @XmlElement(name = "provider_dimension", required = true)
        protected List<ProviderDimensionType> providerDimension;

        /**
         * Gets the value of the providerDimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the providerDimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProviderDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProviderDimensionType }
         * 
         * 
         */
        public List<ProviderDimensionType> getProviderDimension() {
            if (providerDimension == null) {
                providerDimension = new ArrayList<ProviderDimensionType>();
            }
            return this.providerDimension;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="visit_dimension" type="{http://www.i2b2.org/xsd/hive/pdo/}visit_dimensionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "visitDimension"
    })
    public static class VisitDimensionSet {

        @XmlElement(name = "visit_dimension", required = true)
        protected List<VisitDimensionType> visitDimension;

        /**
         * Gets the value of the visitDimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the visitDimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVisitDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VisitDimensionType }
         * 
         * 
         */
        public List<VisitDimensionType> getVisitDimension() {
            if (visitDimension == null) {
                visitDimension = new ArrayList<VisitDimensionType>();
            }
            return this.visitDimension;
        }

    }

}
