//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:15 PM MESZ 
//


package edu.harvard.i2b2.core.datavo.pdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * One row of data from the visit_dimension table.
 * 
 * <p>Java class for visit_dimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="visit_dimensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}encounter_idChoice"/>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}patient_idChoice"/>
 *         &lt;element name="inout_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}InOut_CdType" minOccurs="0"/>
 *         &lt;element name="location_cd" type="{http://www.i2b2.org/xsd/hive/pdo/}Location_CdType" minOccurs="0"/>
 *         &lt;element name="location_path" type="{http://www.i2b2.org/xsd/hive/pdo/}Location_PathType" minOccurs="0"/>
 *         &lt;element name="start_date" type="{http://www.i2b2.org/xsd/hive/pdo/}Start_DateType" minOccurs="0"/>
 *         &lt;element name="end_date" type="{http://www.i2b2.org/xsd/hive/pdo/}End_DateType" minOccurs="0"/>
 *         &lt;element name="visit_blob" type="{http://www.i2b2.org/xsd/hive/pdo/}Visit_BlobType" minOccurs="0"/>
 *         &lt;group ref="{http://www.i2b2.org/xsd/hive/pdo/}annotationGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "visit_dimensionType", propOrder = {
    "encounterNum",
    "encounterId",
    "encounterIde",
    "patientNum",
    "patientId",
    "patientIde",
    "inoutCd",
    "locationCd",
    "locationPath",
    "startDate",
    "endDate",
    "visitBlob",
    "updateDate",
    "downloadDate",
    "importDate",
    "sourcesystemCd",
    "uploadId"
})
public class VisitDimensionType {

    @XmlElement(name = "encounter_num")
    protected Integer encounterNum;
    @XmlElement(name = "encounter_id")
    protected EncounterIdType encounterId;
    @XmlElement(name = "encounter_ide")
    protected EncounterIdeType encounterIde;
    @XmlElement(name = "patient_num")
    protected Integer patientNum;
    @XmlElement(name = "patient_id")
    protected PatientIdType patientId;
    @XmlElement(name = "patient_ide")
    protected PatientIdeType patientIde;
    @XmlElement(name = "inout_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inoutCd;
    @XmlElement(name = "location_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locationCd;
    @XmlElement(name = "location_path")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locationPath;
    @XmlElement(name = "start_date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "end_date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "visit_blob")
    protected VisitBlobType visitBlob;
    @XmlElement(name = "update_date")
    protected XMLGregorianCalendar updateDate;
    @XmlElement(name = "download_date")
    protected XMLGregorianCalendar downloadDate;
    @XmlElement(name = "import_date")
    protected XMLGregorianCalendar importDate;
    @XmlElement(name = "sourcesystem_cd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourcesystemCd;
    @XmlElement(name = "upload_id")
    protected Integer uploadId;

    /**
     * Gets the value of the encounterNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEncounterNum() {
        return encounterNum;
    }

    /**
     * Sets the value of the encounterNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEncounterNum(Integer value) {
        this.encounterNum = value;
    }

    /**
     * Gets the value of the encounterId property.
     * 
     * @return
     *     possible object is
     *     {@link EncounterIdType }
     *     
     */
    public EncounterIdType getEncounterId() {
        return encounterId;
    }

    /**
     * Sets the value of the encounterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncounterIdType }
     *     
     */
    public void setEncounterId(EncounterIdType value) {
        this.encounterId = value;
    }

    /**
     * Gets the value of the encounterIde property.
     * 
     * @return
     *     possible object is
     *     {@link EncounterIdeType }
     *     
     */
    public EncounterIdeType getEncounterIde() {
        return encounterIde;
    }

    /**
     * Sets the value of the encounterIde property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncounterIdeType }
     *     
     */
    public void setEncounterIde(EncounterIdeType value) {
        this.encounterIde = value;
    }

    /**
     * Gets the value of the patientNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPatientNum() {
        return patientNum;
    }

    /**
     * Sets the value of the patientNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPatientNum(Integer value) {
        this.patientNum = value;
    }

    /**
     * Gets the value of the patientId property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdType }
     *     
     */
    public PatientIdType getPatientId() {
        return patientId;
    }

    /**
     * Sets the value of the patientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdType }
     *     
     */
    public void setPatientId(PatientIdType value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the patientIde property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdeType }
     *     
     */
    public PatientIdeType getPatientIde() {
        return patientIde;
    }

    /**
     * Sets the value of the patientIde property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdeType }
     *     
     */
    public void setPatientIde(PatientIdeType value) {
        this.patientIde = value;
    }

    /**
     * Gets the value of the inoutCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInoutCd() {
        return inoutCd;
    }

    /**
     * Sets the value of the inoutCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInoutCd(String value) {
        this.inoutCd = value;
    }

    /**
     * Gets the value of the locationCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCd() {
        return locationCd;
    }

    /**
     * Sets the value of the locationCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationCd(String value) {
        this.locationCd = value;
    }

    /**
     * Gets the value of the locationPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationPath() {
        return locationPath;
    }

    /**
     * Sets the value of the locationPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationPath(String value) {
        this.locationPath = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the visitBlob property.
     * 
     * @return
     *     possible object is
     *     {@link VisitBlobType }
     *     
     */
    public VisitBlobType getVisitBlob() {
        return visitBlob;
    }

    /**
     * Sets the value of the visitBlob property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitBlobType }
     *     
     */
    public void setVisitBlob(VisitBlobType value) {
        this.visitBlob = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the downloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDownloadDate() {
        return downloadDate;
    }

    /**
     * Sets the value of the downloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDownloadDate(XMLGregorianCalendar value) {
        this.downloadDate = value;
    }

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportDate(XMLGregorianCalendar value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the sourcesystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesystemCd() {
        return sourcesystemCd;
    }

    /**
     * Sets the value of the sourcesystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesystemCd(String value) {
        this.sourcesystemCd = value;
    }

    /**
     * Gets the value of the uploadId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * Sets the value of the uploadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUploadId(Integer value) {
        this.uploadId = value;
    }

}
