//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:30 PM MESZ 
//


package de.erlangen.i2b2.giri.datavo.giriconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RscriptletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RscriptletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settings" type="{http://www.i2b2.org/xsd/cell/giriconf/1.0/}settingsType" minOccurs="0"/>
 *         &lt;element name="additionalInputs" type="{http://www.i2b2.org/xsd/cell/giriconf/1.0/}additionalInputsType" minOccurs="0"/>
 *         &lt;element name="customOutputs" type="{http://www.i2b2.org/xsd/cell/giriconf/1.0/}customOutputsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RscriptletType", propOrder = {
    "settings",
    "additionalInputs",
    "customOutputs"
})
public class RscriptletType {

    protected SettingsType settings;
    protected AdditionalInputsType additionalInputs;
    protected CustomOutputsType customOutputs;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link SettingsType }
     *     
     */
    public SettingsType getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettingsType }
     *     
     */
    public void setSettings(SettingsType value) {
        this.settings = value;
    }

    /**
     * Gets the value of the additionalInputs property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInputsType }
     *     
     */
    public AdditionalInputsType getAdditionalInputs() {
        return additionalInputs;
    }

    /**
     * Sets the value of the additionalInputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInputsType }
     *     
     */
    public void setAdditionalInputs(AdditionalInputsType value) {
        this.additionalInputs = value;
    }

    /**
     * Gets the value of the customOutputs property.
     * 
     * @return
     *     possible object is
     *     {@link CustomOutputsType }
     *     
     */
    public CustomOutputsType getCustomOutputs() {
        return customOutputs;
    }

    /**
     * Sets the value of the customOutputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomOutputsType }
     *     
     */
    public void setCustomOutputs(CustomOutputsType value) {
        this.customOutputs = value;
    }

}
