setwd('/home/ubuntu/i2b2/reportScripts')
options( java.parameters = "-Xmx2g" )

report.patients <- c()
report.observations <- c()
report.input <- c()
report.output <- list()
report.concept.names <- c()
report.modifiers <- c()
report.events <- c()
report.observers <- c()