//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:30 PM MESZ 
//


package de.erlangen.i2b2.giri.datavo.girimessages;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.erlangen.i2b2.giri.datavo.girimessages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RScriptlets_QNAME = new QName("http://www.i2b2.org/xsd/cell/giri/1.0/", "RScriptlets");
    private final static QName _RScriptletResult_QNAME = new QName("http://www.i2b2.org/xsd/cell/giri/1.0/", "RScriptletResult");
    private final static QName _RResults_QNAME = new QName("http://www.i2b2.org/xsd/cell/giri/1.0/", "RResults");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.erlangen.i2b2.giri.datavo.girimessages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientSetsType }
     * 
     */
    public PatientSetsType createPatientSetsType() {
        return new PatientSetsType();
    }

    /**
     * Create an instance of {@link RResultsType }
     * 
     */
    public RResultsType createRResultsType() {
        return new RResultsType();
    }

    /**
     * Create an instance of {@link AdditionalInputType }
     * 
     */
    public AdditionalInputType createAdditionalInputType() {
        return new AdditionalInputType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link InputParameterType }
     * 
     */
    public InputParameterType createInputParameterType() {
        return new InputParameterType();
    }

    /**
     * Create an instance of {@link RScriptletsType }
     * 
     */
    public RScriptletsType createRScriptletsType() {
        return new RScriptletsType();
    }

    /**
     * Create an instance of {@link RScriptletResultType }
     * 
     */
    public RScriptletResultType createRScriptletResultType() {
        return new RScriptletResultType();
    }

    /**
     * Create an instance of {@link ConceptsType }
     * 
     */
    public ConceptsType createConceptsType() {
        return new ConceptsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RScriptletsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/giri/1.0/", name = "RScriptlets")
    public JAXBElement<RScriptletsType> createRScriptlets(RScriptletsType value) {
        return new JAXBElement<RScriptletsType>(_RScriptlets_QNAME, RScriptletsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RScriptletResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/giri/1.0/", name = "RScriptletResult")
    public JAXBElement<RScriptletResultType> createRScriptletResult(RScriptletResultType value) {
        return new JAXBElement<RScriptletResultType>(_RScriptletResult_QNAME, RScriptletResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RResultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/giri/1.0/", name = "RResults")
    public JAXBElement<RResultsType> createRResults(RResultsType value) {
        return new JAXBElement<RResultsType>(_RResults_QNAME, RResultsType.class, null, value);
    }

}
