//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:30 PM MESZ 
//


package de.erlangen.i2b2.giri.datavo.girimessages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RScriptletResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RScriptletResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RScriptletName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QTSUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="patientSets" type="{http://www.i2b2.org/xsd/cell/giri/1.0/}patientSetsType"/>
 *         &lt;element name="concepts" type="{http://www.i2b2.org/xsd/cell/giri/1.0/}conceptsType"/>
 *         &lt;element name="additionalInput" type="{http://www.i2b2.org/xsd/cell/giri/1.0/}additionalInputType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RScriptletResultType", propOrder = {
    "rScriptletName",
    "qtsUrl",
    "patientSets",
    "concepts",
    "additionalInput"
})
public class RScriptletResultType {

    @XmlElement(name = "RScriptletName", required = true)
    protected String rScriptletName;
    @XmlElement(name = "QTSUrl", required = true)
    protected String qtsUrl;
    @XmlElement(required = true)
    protected PatientSetsType patientSets;
    @XmlElement(required = true)
    protected ConceptsType concepts;
    protected AdditionalInputType additionalInput;

    /**
     * Gets the value of the rScriptletName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRScriptletName() {
        return rScriptletName;
    }

    /**
     * Sets the value of the rScriptletName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRScriptletName(String value) {
        this.rScriptletName = value;
    }

    /**
     * Gets the value of the qtsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTSUrl() {
        return qtsUrl;
    }

    /**
     * Sets the value of the qtsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTSUrl(String value) {
        this.qtsUrl = value;
    }

    /**
     * Gets the value of the patientSets property.
     * 
     * @return
     *     possible object is
     *     {@link PatientSetsType }
     *     
     */
    public PatientSetsType getPatientSets() {
        return patientSets;
    }

    /**
     * Sets the value of the patientSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientSetsType }
     *     
     */
    public void setPatientSets(PatientSetsType value) {
        this.patientSets = value;
    }

    /**
     * Gets the value of the concepts property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptsType }
     *     
     */
    public ConceptsType getConcepts() {
        return concepts;
    }

    /**
     * Sets the value of the concepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptsType }
     *     
     */
    public void setConcepts(ConceptsType value) {
        this.concepts = value;
    }

    /**
     * Gets the value of the additionalInput property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInputType }
     *     
     */
    public AdditionalInputType getAdditionalInput() {
        return additionalInput;
    }

    /**
     * Sets the value of the additionalInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInputType }
     *     
     */
    public void setAdditionalInput(AdditionalInputType value) {
        this.additionalInput = value;
    }

}
