//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 11:05:30 PM MESZ 
//


package de.erlangen.i2b2.giri.datavo.girimessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.erlangen.i2b2.giri.datavo.giriconfig.RscriptletType;


/**
 * <p>Java class for RScriptletsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RScriptletsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faultyScriptlets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rscriptlet" type="{http://www.i2b2.org/xsd/cell/giriconf/1.0/}RscriptletType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RScriptletsType", propOrder = {
    "faultyScriptlets",
    "rscriptlet"
})
public class RScriptletsType {

    @XmlElement(required = true)
    protected String faultyScriptlets;
    protected List<RscriptletType> rscriptlet;

    /**
     * Gets the value of the faultyScriptlets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultyScriptlets() {
        return faultyScriptlets;
    }

    /**
     * Sets the value of the faultyScriptlets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultyScriptlets(String value) {
        this.faultyScriptlets = value;
    }

    /**
     * Gets the value of the rscriptlet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rscriptlet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRscriptlet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RscriptletType }
     * 
     * 
     */
    public List<RscriptletType> getRscriptlet() {
        if (rscriptlet == null) {
            rscriptlet = new ArrayList<RscriptletType>();
        }
        return this.rscriptlet;
    }

}
